### ISSUE TITLE
Nice site! 👍🏽❤️

### ISSUE THREAD

**Issue by codebender828** [rxmii4269/My-Portfolio-v2#11]
Thanks for using Chakra UI Vue! Your site looks amazing! Hope you don't mind me featuring it!

**Comment by rxmii4269** [comment]
Hey! I have no problem with you featuring it!, and thank you for creating a great framework, I'll definitely be using it in future projects.

**Comment by codebender828** [comment]
Amazing! Let me know if there's any way you'd like to be a part of the community in the future. We're always looking for help and ideas and more contributors to the project! 😁
